server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://root:123456@192.168.3.6:27017
      database: xc_cms
  rabbitmq:
    host: 192.168.3.6
    port: 5672
    username: admin
    password: admin
    virtualHost: /
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0